### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [pbryan/jane-addams_democracy-and-social-ethics#1]
# General Issues:

- [x] Re-run `se modernize-spelling .` and commit the changes.

# chapter-4.xhtml:

- [x] Remove the italics around `globus hystericus`. It appears in MW.

# content.opf

- [x] In the short description, you need to remove/replace `Addams` since the short description shouldn't have proper names ([SEMOS 9.6.1.2](https://standardebooks.org/manual/1.8.0/9-metadata#9.6.1.2)).

- [x] I recommend a `Nonfiction` tag for this book.

**Comment by pbryan** [comment]
I've completed the above tasks.

**Comment by EmmaSweeney** [comment]
Sorry, I wasn't clear! You can have both `Philosophy` and `Nonfiction` tags for this book.

**Comment by pbryan** [comment]
Ah, OK. Rebased!
